/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectDetailsRouteImport } from './routes/project-details'
import { Route as ProjectBuilderRouteImport } from './routes/project-builder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EcosystemNavigatorRouteImport } from './routes/ecosystem-navigator'
import { Route as EcosystemDashboardRouteImport } from './routes/ecosystem-dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiPlanRouteImport } from './routes/ai-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as SandboxTaskPanelV3RouteImport } from './routes/sandbox.task-panel-v3'
import { Route as SandboxTaskPanelLiveRouteImport } from './routes/sandbox.task-panel-live'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProfileAppearanceRouteImport } from './routes/profile.appearance'
import { Route as DemoFounderRouteImport } from './routes/demo.founder'
import { Route as DemoCollaboratorRouteImport } from './routes/demo.collaborator'
import { Route as DemoFounderIndexRouteImport } from './routes/demo.founder.index'
import { Route as ProjectProjectIdProjectDashboardRouteImport } from './routes/project.$projectId_.project-dashboard'
import { Route as ProjectProjectIdGoalsRouteImport } from './routes/project.$projectId_.goals'
import { Route as DemoInvestorPortfolioRouteImport } from './routes/demo.investor.portfolio'
import { Route as DemoFounderNavigatorRouteImport } from './routes/demo.founder.navigator'
import { Route as DemoFounderDashboardRouteImport } from './routes/demo.founder.dashboard'
import { Route as DemoFounderCompanionRouteImport } from './routes/demo.founder.companion'

const ProjectDetailsRoute = ProjectDetailsRouteImport.update({
  id: '/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectBuilderRoute = ProjectBuilderRouteImport.update({
  id: '/project-builder',
  path: '/project-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemNavigatorRoute = EcosystemNavigatorRouteImport.update({
  id: '/ecosystem-navigator',
  path: '/ecosystem-navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemDashboardRoute = EcosystemDashboardRouteImport.update({
  id: '/ecosystem-dashboard',
  path: '/ecosystem-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlanRoute = AiPlanRouteImport.update({
  id: '/ai-plan',
  path: '/ai-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxTaskPanelV3Route = SandboxTaskPanelV3RouteImport.update({
  id: '/sandbox/task-panel-v3',
  path: '/sandbox/task-panel-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxTaskPanelLiveRoute = SandboxTaskPanelLiveRouteImport.update({
  id: '/sandbox/task-panel-live',
  path: '/sandbox/task-panel-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAppearanceRoute = ProfileAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => ProfileRoute,
} as any)
const DemoFounderRoute = DemoFounderRouteImport.update({
  id: '/demo/founder',
  path: '/demo/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCollaboratorRoute = DemoCollaboratorRouteImport.update({
  id: '/demo/collaborator',
  path: '/demo/collaborator',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFounderIndexRoute = DemoFounderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoFounderRoute,
} as any)
const ProjectProjectIdProjectDashboardRoute =
  ProjectProjectIdProjectDashboardRouteImport.update({
    id: '/project/$projectId_/project-dashboard',
    path: '/project/$projectId/project-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectProjectIdGoalsRoute = ProjectProjectIdGoalsRouteImport.update({
  id: '/project/$projectId_/goals',
  path: '/project/$projectId/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInvestorPortfolioRoute = DemoInvestorPortfolioRouteImport.update({
  id: '/demo/investor/portfolio',
  path: '/demo/investor/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFounderNavigatorRoute = DemoFounderNavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => DemoFounderRoute,
} as any)
const DemoFounderDashboardRoute = DemoFounderDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoFounderRoute,
} as any)
const DemoFounderCompanionRoute = DemoFounderCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => DemoFounderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-plan': typeof AiPlanRoute
  '/auth': typeof AuthRoute
  '/ecosystem-dashboard': typeof EcosystemDashboardRoute
  '/ecosystem-navigator': typeof EcosystemNavigatorRoute
  '/home': typeof HomeRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRouteWithChildren
  '/project-builder': typeof ProjectBuilderRoute
  '/project-details': typeof ProjectDetailsRoute
  '/demo/collaborator': typeof DemoCollaboratorRoute
  '/demo/founder': typeof DemoFounderRouteWithChildren
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/sandbox/task-panel-live': typeof SandboxTaskPanelLiveRoute
  '/sandbox/task-panel-v3': typeof SandboxTaskPanelV3Route
  '/task/$taskId': typeof TaskTaskIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/demo/founder/companion': typeof DemoFounderCompanionRoute
  '/demo/founder/dashboard': typeof DemoFounderDashboardRoute
  '/demo/founder/navigator': typeof DemoFounderNavigatorRoute
  '/demo/investor/portfolio': typeof DemoInvestorPortfolioRoute
  '/project/$projectId/goals': typeof ProjectProjectIdGoalsRoute
  '/project/$projectId/project-dashboard': typeof ProjectProjectIdProjectDashboardRoute
  '/demo/founder/': typeof DemoFounderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-plan': typeof AiPlanRoute
  '/auth': typeof AuthRoute
  '/ecosystem-dashboard': typeof EcosystemDashboardRoute
  '/ecosystem-navigator': typeof EcosystemNavigatorRoute
  '/home': typeof HomeRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/project-builder': typeof ProjectBuilderRoute
  '/project-details': typeof ProjectDetailsRoute
  '/demo/collaborator': typeof DemoCollaboratorRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/sandbox/task-panel-live': typeof SandboxTaskPanelLiveRoute
  '/sandbox/task-panel-v3': typeof SandboxTaskPanelV3Route
  '/task/$taskId': typeof TaskTaskIdRoute
  '/profile': typeof ProfileIndexRoute
  '/demo/founder/companion': typeof DemoFounderCompanionRoute
  '/demo/founder/dashboard': typeof DemoFounderDashboardRoute
  '/demo/founder/navigator': typeof DemoFounderNavigatorRoute
  '/demo/investor/portfolio': typeof DemoInvestorPortfolioRoute
  '/project/$projectId/goals': typeof ProjectProjectIdGoalsRoute
  '/project/$projectId/project-dashboard': typeof ProjectProjectIdProjectDashboardRoute
  '/demo/founder': typeof DemoFounderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-plan': typeof AiPlanRoute
  '/auth': typeof AuthRoute
  '/ecosystem-dashboard': typeof EcosystemDashboardRoute
  '/ecosystem-navigator': typeof EcosystemNavigatorRoute
  '/home': typeof HomeRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRouteWithChildren
  '/project-builder': typeof ProjectBuilderRoute
  '/project-details': typeof ProjectDetailsRoute
  '/demo/collaborator': typeof DemoCollaboratorRoute
  '/demo/founder': typeof DemoFounderRouteWithChildren
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/sandbox/task-panel-live': typeof SandboxTaskPanelLiveRoute
  '/sandbox/task-panel-v3': typeof SandboxTaskPanelV3Route
  '/task/$taskId': typeof TaskTaskIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/demo/founder/companion': typeof DemoFounderCompanionRoute
  '/demo/founder/dashboard': typeof DemoFounderDashboardRoute
  '/demo/founder/navigator': typeof DemoFounderNavigatorRoute
  '/demo/investor/portfolio': typeof DemoInvestorPortfolioRoute
  '/project/$projectId_/goals': typeof ProjectProjectIdGoalsRoute
  '/project/$projectId_/project-dashboard': typeof ProjectProjectIdProjectDashboardRoute
  '/demo/founder/': typeof DemoFounderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-plan'
    | '/auth'
    | '/ecosystem-dashboard'
    | '/ecosystem-navigator'
    | '/home'
    | '/journal'
    | '/navigator'
    | '/notes'
    | '/portfolio'
    | '/profile'
    | '/project-builder'
    | '/project-details'
    | '/demo/collaborator'
    | '/demo/founder'
    | '/profile/appearance'
    | '/project/$projectId'
    | '/sandbox/task-panel-live'
    | '/sandbox/task-panel-v3'
    | '/task/$taskId'
    | '/profile/'
    | '/demo/founder/companion'
    | '/demo/founder/dashboard'
    | '/demo/founder/navigator'
    | '/demo/investor/portfolio'
    | '/project/$projectId/goals'
    | '/project/$projectId/project-dashboard'
    | '/demo/founder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-plan'
    | '/auth'
    | '/ecosystem-dashboard'
    | '/ecosystem-navigator'
    | '/home'
    | '/journal'
    | '/navigator'
    | '/notes'
    | '/portfolio'
    | '/project-builder'
    | '/project-details'
    | '/demo/collaborator'
    | '/profile/appearance'
    | '/project/$projectId'
    | '/sandbox/task-panel-live'
    | '/sandbox/task-panel-v3'
    | '/task/$taskId'
    | '/profile'
    | '/demo/founder/companion'
    | '/demo/founder/dashboard'
    | '/demo/founder/navigator'
    | '/demo/investor/portfolio'
    | '/project/$projectId/goals'
    | '/project/$projectId/project-dashboard'
    | '/demo/founder'
  id:
    | '__root__'
    | '/'
    | '/ai-plan'
    | '/auth'
    | '/ecosystem-dashboard'
    | '/ecosystem-navigator'
    | '/home'
    | '/journal'
    | '/navigator'
    | '/notes'
    | '/portfolio'
    | '/profile'
    | '/project-builder'
    | '/project-details'
    | '/demo/collaborator'
    | '/demo/founder'
    | '/profile/appearance'
    | '/project/$projectId'
    | '/sandbox/task-panel-live'
    | '/sandbox/task-panel-v3'
    | '/task/$taskId'
    | '/profile/'
    | '/demo/founder/companion'
    | '/demo/founder/dashboard'
    | '/demo/founder/navigator'
    | '/demo/investor/portfolio'
    | '/project/$projectId_/goals'
    | '/project/$projectId_/project-dashboard'
    | '/demo/founder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPlanRoute: typeof AiPlanRoute
  AuthRoute: typeof AuthRoute
  EcosystemDashboardRoute: typeof EcosystemDashboardRoute
  EcosystemNavigatorRoute: typeof EcosystemNavigatorRoute
  HomeRoute: typeof HomeRoute
  JournalRoute: typeof JournalRoute
  NavigatorRoute: typeof NavigatorRoute
  NotesRoute: typeof NotesRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProjectBuilderRoute: typeof ProjectBuilderRoute
  ProjectDetailsRoute: typeof ProjectDetailsRoute
  DemoCollaboratorRoute: typeof DemoCollaboratorRoute
  DemoFounderRoute: typeof DemoFounderRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  SandboxTaskPanelLiveRoute: typeof SandboxTaskPanelLiveRoute
  SandboxTaskPanelV3Route: typeof SandboxTaskPanelV3Route
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  DemoInvestorPortfolioRoute: typeof DemoInvestorPortfolioRoute
  ProjectProjectIdGoalsRoute: typeof ProjectProjectIdGoalsRoute
  ProjectProjectIdProjectDashboardRoute: typeof ProjectProjectIdProjectDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-details': {
      id: '/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof ProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-builder': {
      id: '/project-builder'
      path: '/project-builder'
      fullPath: '/project-builder'
      preLoaderRoute: typeof ProjectBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem-navigator': {
      id: '/ecosystem-navigator'
      path: '/ecosystem-navigator'
      fullPath: '/ecosystem-navigator'
      preLoaderRoute: typeof EcosystemNavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem-dashboard': {
      id: '/ecosystem-dashboard'
      path: '/ecosystem-dashboard'
      fullPath: '/ecosystem-dashboard'
      preLoaderRoute: typeof EcosystemDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-plan': {
      id: '/ai-plan'
      path: '/ai-plan'
      fullPath: '/ai-plan'
      preLoaderRoute: typeof AiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/task-panel-v3': {
      id: '/sandbox/task-panel-v3'
      path: '/sandbox/task-panel-v3'
      fullPath: '/sandbox/task-panel-v3'
      preLoaderRoute: typeof SandboxTaskPanelV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/task-panel-live': {
      id: '/sandbox/task-panel-live'
      path: '/sandbox/task-panel-live'
      fullPath: '/sandbox/task-panel-live'
      preLoaderRoute: typeof SandboxTaskPanelLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/appearance': {
      id: '/profile/appearance'
      path: '/appearance'
      fullPath: '/profile/appearance'
      preLoaderRoute: typeof ProfileAppearanceRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/demo/founder': {
      id: '/demo/founder'
      path: '/demo/founder'
      fullPath: '/demo/founder'
      preLoaderRoute: typeof DemoFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/collaborator': {
      id: '/demo/collaborator'
      path: '/demo/collaborator'
      fullPath: '/demo/collaborator'
      preLoaderRoute: typeof DemoCollaboratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/founder/': {
      id: '/demo/founder/'
      path: '/'
      fullPath: '/demo/founder/'
      preLoaderRoute: typeof DemoFounderIndexRouteImport
      parentRoute: typeof DemoFounderRoute
    }
    '/project/$projectId_/project-dashboard': {
      id: '/project/$projectId_/project-dashboard'
      path: '/project/$projectId/project-dashboard'
      fullPath: '/project/$projectId/project-dashboard'
      preLoaderRoute: typeof ProjectProjectIdProjectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId_/goals': {
      id: '/project/$projectId_/goals'
      path: '/project/$projectId/goals'
      fullPath: '/project/$projectId/goals'
      preLoaderRoute: typeof ProjectProjectIdGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/investor/portfolio': {
      id: '/demo/investor/portfolio'
      path: '/demo/investor/portfolio'
      fullPath: '/demo/investor/portfolio'
      preLoaderRoute: typeof DemoInvestorPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/founder/navigator': {
      id: '/demo/founder/navigator'
      path: '/navigator'
      fullPath: '/demo/founder/navigator'
      preLoaderRoute: typeof DemoFounderNavigatorRouteImport
      parentRoute: typeof DemoFounderRoute
    }
    '/demo/founder/dashboard': {
      id: '/demo/founder/dashboard'
      path: '/dashboard'
      fullPath: '/demo/founder/dashboard'
      preLoaderRoute: typeof DemoFounderDashboardRouteImport
      parentRoute: typeof DemoFounderRoute
    }
    '/demo/founder/companion': {
      id: '/demo/founder/companion'
      path: '/companion'
      fullPath: '/demo/founder/companion'
      preLoaderRoute: typeof DemoFounderCompanionRouteImport
      parentRoute: typeof DemoFounderRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileAppearanceRoute: typeof ProfileAppearanceRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAppearanceRoute: ProfileAppearanceRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface DemoFounderRouteChildren {
  DemoFounderCompanionRoute: typeof DemoFounderCompanionRoute
  DemoFounderDashboardRoute: typeof DemoFounderDashboardRoute
  DemoFounderNavigatorRoute: typeof DemoFounderNavigatorRoute
  DemoFounderIndexRoute: typeof DemoFounderIndexRoute
}

const DemoFounderRouteChildren: DemoFounderRouteChildren = {
  DemoFounderCompanionRoute: DemoFounderCompanionRoute,
  DemoFounderDashboardRoute: DemoFounderDashboardRoute,
  DemoFounderNavigatorRoute: DemoFounderNavigatorRoute,
  DemoFounderIndexRoute: DemoFounderIndexRoute,
}

const DemoFounderRouteWithChildren = DemoFounderRoute._addFileChildren(
  DemoFounderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPlanRoute: AiPlanRoute,
  AuthRoute: AuthRoute,
  EcosystemDashboardRoute: EcosystemDashboardRoute,
  EcosystemNavigatorRoute: EcosystemNavigatorRoute,
  HomeRoute: HomeRoute,
  JournalRoute: JournalRoute,
  NavigatorRoute: NavigatorRoute,
  NotesRoute: NotesRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProjectBuilderRoute: ProjectBuilderRoute,
  ProjectDetailsRoute: ProjectDetailsRoute,
  DemoCollaboratorRoute: DemoCollaboratorRoute,
  DemoFounderRoute: DemoFounderRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  SandboxTaskPanelLiveRoute: SandboxTaskPanelLiveRoute,
  SandboxTaskPanelV3Route: SandboxTaskPanelV3Route,
  TaskTaskIdRoute: TaskTaskIdRoute,
  DemoInvestorPortfolioRoute: DemoInvestorPortfolioRoute,
  ProjectProjectIdGoalsRoute: ProjectProjectIdGoalsRoute,
  ProjectProjectIdProjectDashboardRoute: ProjectProjectIdProjectDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
