/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectBuilderRouteImport } from './routes/project-builder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileAppearanceRouteImport } from './routes/profile.appearance'

const ProjectBuilderRoute = ProjectBuilderRouteImport.update({
  id: '/project-builder',
  path: '/project-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAppearanceRoute = ProfileAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/project-builder': typeof ProjectBuilderRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/project-builder': typeof ProjectBuilderRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRouteWithChildren
  '/project-builder': typeof ProjectBuilderRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notes'
    | '/profile'
    | '/project-builder'
    | '/profile/appearance'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notes'
    | '/project-builder'
    | '/profile/appearance'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/notes'
    | '/profile'
    | '/project-builder'
    | '/profile/appearance'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProjectBuilderRoute: typeof ProjectBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-builder': {
      id: '/project-builder'
      path: '/project-builder'
      fullPath: '/project-builder'
      preLoaderRoute: typeof ProjectBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/appearance': {
      id: '/profile/appearance'
      path: '/appearance'
      fullPath: '/profile/appearance'
      preLoaderRoute: typeof ProfileAppearanceRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileAppearanceRoute: typeof ProfileAppearanceRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAppearanceRoute: ProfileAppearanceRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProjectBuilderRoute: ProjectBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
